default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: memair_ihealth_development
  username: memair_ihealth_development
  password: password

test:
  <<: *default
  database: memair_ihealth_test
  username: memair_ihealth_test
  password: password

production:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: "memair_ihealth"
